[package]
name = "pick"
version = "0.1.0"
authors = ["Alejandro Sior <aho@sior.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.7.0"
colors-transform = "0.2.11"
colored = "2"
